basePath: /api/v1
definitions:
  model.PageData:
    properties:
      count:
        type: integer
      data: {}
      pageNo:
        type: integer
      pageSize:
        type: integer
    type: object
  model.TestResult:
    properties:
      amount:
        type: number
      createAt:
        type: string
      id:
        type: integer
      name:
        type: string
      status:
        type: integer
      userId:
        type: integer
    type: object
  result.Result-model_PageData:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/model.PageData'
      message:
        type: string
      timeStamp:
        type: integer
    type: object
host: localhost:18089
info:
  contact: {}
  description: This is a sample server celler server.
  title: XXX API
  version: "1.0"
paths:
  /test/query:
    get:
      consumes:
      - application/json
      description: get list by ID
      parameters:
      - in: query
        name: id
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        name: pageNo
        type: integer
      - in: query
        name: pageSize
        type: integer
      - in: query
        name: status
        type: integer
      - in: query
        name: userId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/result.Result-model_PageData'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/model.PageData'
                  - properties:
                      data:
                        items:
                          $ref: '#/definitions/model.TestResult'
                        type: array
                    type: object
              type: object
      summary: test data list
      tags:
      - test
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
